/*
 * Copyright 2026 Ronny Trommer <ronny@no42.org>
 * SPDX-License-Identifier: Apache-2.0
 */

// Command gnmi-catalog generates an nl6 gNMI path catalogue
// (resources/<type>/gnmi.json) from YANG models and a bindings file.
//
//	gnmi-catalog -yang <dir,...> [-path <dir,...>] -bindings <file> -out <file>
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/openconfig/goyang/pkg/yang"
)

type bindings struct {
	Comment      string           `json:"comment"`
	Vendor       string           `json:"vendor"`
	Notification json.RawMessage  `json:"notification"`
	Components   json.RawMessage  `json:"components"`
	Neighbors    json.RawMessage  `json:"neighbors"`
	Subtrees     []bindingSubtree `json:"subtrees"`
}

type bindingSubtree struct {
	Path    string            `json:"path"`
	Origin  string            `json:"origin"`
	Aliases []string          `json:"aliases"`
	Keys    json.RawMessage   `json:"keys"`
	Module  string            `json:"module"`
	Leaves  map[string]string `json:"leaves"`
	Types   map[string]string `json:"types"`
	// Filters narrows a leaf to the components matching the value
	// (the `components` key-source vocabulary); copied to the emitted
	// leaf's `filter`. A per-component leaf belongs in the entry's one
	// subtree with a filter, never in a second subtree on the same
	// path, which the loader refuses (nl6#765).
	Filters map[string]string `json:"filters"`
	Extra   map[string]struct {
		Type string `json:"type"`
		Gen  string `json:"gen"`
	} `json:"extra"`
}

type outLeaf struct {
	Name   string   `json:"name"`
	Type   string   `json:"type"`
	Enum   []string `json:"enum,omitempty"`
	Gen    string   `json:"gen"`
	Filter string   `json:"filter,omitempty"`
}

type outSubtree struct {
	Path    string          `json:"path"`
	Origin  string          `json:"origin"`
	Aliases []string        `json:"aliases,omitempty"`
	Keys    json.RawMessage `json:"keys"`
	Leaves  []outLeaf       `json:"leaves"`
}

type outModel struct {
	Name         string `json:"name"`
	Organization string `json:"organization"`
	Version      string `json:"version"`
}

type outCatalog struct {
	Comment      string          `json:"comment"`
	Vendor       string          `json:"vendor"`
	Notification json.RawMessage `json:"notification"`
	Models       []outModel      `json:"models"`
	Components   json.RawMessage `json:"components"`
	Neighbors    json.RawMessage `json:"neighbors"`
	Subtrees     []outSubtree    `json:"subtrees"`
}

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, "gnmi-catalog:", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	flags := flag.NewFlagSet("gnmi-catalog", flag.ContinueOnError)
	yangDirs := flags.String("yang", "", "comma-separated directories searched recursively for .yang files")
	importDirs := flags.String("path", "", "comma-separated directories searched only to resolve imports (optional)")
	bindingsPath := flags.String("bindings", "", "bindings JSON file")
	outPath := flags.String("out", "", "output catalogue path")
	if err := flags.Parse(args); err != nil {
		return err
	}
	if *yangDirs == "" || *bindingsPath == "" || *outPath == "" {
		return errors.New("-yang, -bindings and -out are required")
	}
	raw, err := os.ReadFile(*bindingsPath)
	if err != nil {
		return err
	}
	var b bindings
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&b); err != nil {
		return fmt.Errorf("bindings: %w", err)
	}
	var imports []string
	if *importDirs != "" {
		imports = strings.Split(*importDirs, ",")
	}
	ms, err := loadModules(strings.Split(*yangDirs, ","), imports)
	if err != nil {
		return err
	}
	out := outCatalog{Comment: "GENERATED by go/cmd/gnmi-catalog from " + filepath.Base(*bindingsPath) + "; do not edit. " + b.Comment,
		Vendor: b.Vendor, Notification: b.Notification, Components: b.Components, Neighbors: b.Neighbors}
	if out.Components == nil {
		out.Components = json.RawMessage("[]")
	}
	if out.Neighbors == nil {
		out.Neighbors = json.RawMessage("[]")
	}
	models := map[string]outModel{}
	for _, st := range b.Subtrees {
		mod := ms.Modules[st.Module]
		if mod == nil {
			return fmt.Errorf("subtree %s: module %q not loaded", st.Path, st.Module)
		}
		root := yang.ToEntry(mod)
		models[mod.Name] = outModel{Name: mod.Name, Organization: strings.TrimSpace(orgOf(mod)), Version: latestRevision(mod)}
		leaves := []outLeaf{}
		names := make([]string, 0, len(st.Leaves))
		for n := range st.Leaves {
			names = append(names, n)
		}
		sort.Strings(names)
		for _, name := range names {
			e, err := lookup(root, st.Path, name)
			if err != nil {
				return fmt.Errorf("subtree %s leaf %s: %w", st.Path, name, err)
			}
			typ, enum := typeOf(e)
			if ov, ok := st.Types[name]; ok {
				typ, enum = ov, nil
			}
			leaves = append(leaves, outLeaf{Name: name, Type: typ, Enum: enum, Gen: st.Leaves[name], Filter: st.Filters[name]})
		}
		extraNames := make([]string, 0, len(st.Extra))
		for n := range st.Extra {
			extraNames = append(extraNames, n)
		}
		sort.Strings(extraNames)
		for _, n := range extraNames {
			leaves = append(leaves, outLeaf{Name: n, Type: st.Extra[n].Type, Gen: st.Extra[n].Gen, Filter: st.Filters[n]})
		}
		for n := range st.Filters {
			if _, ok := st.Leaves[n]; ok {
				continue
			}
			if _, ok := st.Extra[n]; ok {
				continue
			}
			return fmt.Errorf("subtree %s: filter on leaf %s, which is in neither leaves nor extra", st.Path, n)
		}
		keys := st.Keys
		if keys == nil {
			keys = json.RawMessage("[]")
		}
		out.Subtrees = append(out.Subtrees, outSubtree{Path: st.Path, Origin: st.Origin, Aliases: st.Aliases, Keys: keys, Leaves: leaves})
	}
	for _, m := range models {
		out.Models = append(out.Models, m)
	}
	sort.Slice(out.Models, func(i, j int) bool { return out.Models[i].Name < out.Models[j].Name })
	enc, err := json.MarshalIndent(out, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(*outPath, append(enc, '\n'), 0o644) // #nosec G306 -- generated catalogue is committed to the repo; world-readable is intended
}

// knownUnbuildableDeviationTargets are deviation targets that exist in
// the YANG but that goyang never builds: they come from an augment nested
// inside a uses statement (uses aft-common-entry-state { augment counters
// { ... } } in openconfig-aft-ipv4/ipv6), which goyang does not expand.
// Juniper's jnx-openconfig-dev module (24.2R1.17) deviates them.
var knownUnbuildableDeviationTargets = []string{
	"/oc-ni:network-instances/oc-ni:network-instance/oc-ni:afts/oc-ni:ipv4-unicast/oc-ni:ipv4-entry/oc-ni:state/oc-ni:counters/oc-ni:octets-forwarded-backup",
	"/oc-ni:network-instances/oc-ni:network-instance/oc-ni:afts/oc-ni:ipv4-unicast/oc-ni:ipv4-entry/oc-ni:state/oc-ni:counters/oc-ni:packets-forwarded-backup",
	"/oc-ni:network-instances/oc-ni:network-instance/oc-ni:afts/oc-ni:ipv6-unicast/oc-ni:ipv6-entry/oc-ni:state/oc-ni:counters/oc-ni:octets-forwarded-backup",
	"/oc-ni:network-instances/oc-ni:network-instance/oc-ni:afts/oc-ni:ipv6-unicast/oc-ni:ipv6-entry/oc-ni:state/oc-ni:counters/oc-ni:packets-forwarded-backup",
}

// isKnownUnbuildableDeviation reports whether err is goyang's missing
// deviation target error for exactly one of the allowlisted targets.
func isKnownUnbuildableDeviation(err error) bool {
	for _, t := range knownUnbuildableDeviationTargets {
		if err.Error() == "cannot find target node to deviate, "+t {
			return true
		}
	}
	return false
}

// loadModules reads every .yang file under dirs and processes them.
// importDirs are only added to the search path, so a module there is
// loaded when something imports it.
func loadModules(dirs, importDirs []string) (*yang.Modules, error) {
	ms := yang.NewModules()
	for _, d := range importDirs {
		ms.AddPath(strings.TrimSpace(d))
	}
	var files []string
	for _, d := range dirs {
		d = strings.TrimSpace(d)
		err := filepath.WalkDir(d, func(p string, de fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if !de.IsDir() && strings.HasSuffix(p, ".yang") {
				files = append(files, p)
			}
			return nil
		})
		if err != nil {
			return nil, err
		}
		ms.AddPath(d)
	}
	sort.Strings(files)
	for _, f := range files {
		if err := ms.Read(f); err != nil {
			return nil, fmt.Errorf("%s: %w", f, err)
		}
	}
	// Deviations are applied last, and a deviation whose target is
	// missing is skipped without touching the rest of the tree. Only the
	// known unbuildable targets are downgraded to warnings; any other
	// missing target fails generation.
	var sb strings.Builder
	for _, e := range ms.Process() {
		if isKnownUnbuildableDeviation(e) {
			fmt.Fprintln(os.Stderr, "gnmi-catalog: warning:", e)
			continue
		}
		sb.WriteString(e.Error())
		sb.WriteByte('\n')
	}
	if sb.Len() > 0 {
		return nil, errors.New(sb.String())
	}
	return ms, nil
}

// lookup walks root by the subtree path plus the leaf path, ignoring
// keys. A node removed by `deviate not-supported` is absent from the
// Entry tree, so it is reported as missing.
func lookup(root *yang.Entry, subtree, leaf string) (*yang.Entry, error) {
	e := root
	for _, part := range strings.Split(strings.Trim(subtree+"/"+leaf, "/"), "/") {
		if i := strings.IndexByte(part, '['); i >= 0 {
			part = part[:i]
		}
		if part == "" {
			continue
		}
		next := e.Dir[part]
		if next == nil {
			return nil, fmt.Errorf("%q not found under %s", part, e.Path())
		}
		e = next
	}
	if !e.IsLeaf() && !e.IsLeafList() {
		return nil, fmt.Errorf("%s is not a leaf", e.Path())
	}
	return e, nil
}

func typeOf(e *yang.Entry) (string, []string) {
	t := e.Type
	for t.Kind == yang.Yleafref && t.Path != "" {
		// Follow leafrefs until a non-leafref type; each hop resolves
		// its path relative to the entry that declared it.
		if target := e.Find(t.Path); target != nil && target.Type != nil {
			e, t = target, target.Type
			continue
		}
		break
	}
	switch t.Kind {
	case yang.Yenum:
		return "enumeration", enumNames(t.Enum)
	case yang.Yidentityref:
		var names []string
		for _, id := range t.IdentityBase.Values {
			names = append(names, id.Name)
		}
		sort.Strings(names)
		return "identityref", names
	case yang.Ybool:
		return "boolean", nil
	case yang.Ydecimal64:
		return "decimal64", nil
	case yang.Yunion:
		return "union", nil
	}
	return t.Kind.String(), nil // uint64, uint32, int64, string, ...
}

// enumNames lists enum names in value order. For auto-numbered enums
// that is declaration order; EnumType.Names sorts alphabetically.
func enumNames(e *yang.EnumType) []string {
	var names []string
	for _, v := range e.Values() {
		names = append(names, e.Name(v))
	}
	return names
}

func orgOf(m *yang.Module) string {
	if m.Organization != nil {
		return m.Organization.Name
	}
	return ""
}

func latestRevision(m *yang.Module) string {
	best := ""
	for _, r := range m.Revision {
		if r.Name > best {
			best = r.Name
		}
	}
	return best
}
