/*
 * Copyright 2026 Ronny Trommer <ronny@no42.org>
 * SPDX-License-Identifier: Apache-2.0
 */

package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"sort"
	"testing"
)

// nl6#541 changed shipped DATA as well as code: applying the typed-class rule to
// the shipped set for the first time found 45 entries of the class it exists to
// catch. Those edits changed what 31 shipped OIDs put on the wire and removed 14
// others, and the first cut of this change reported that as an aggregate count,
// which is exactly the shape the Block If exists to prevent for the type table.
// A count is not a measurement a reader can check.
//
// So the transition is committed as data and re-derived by the test below: apply
// the INVERSE of every edit to today's corpus and the parent revision's digest
// must come back byte for byte. Nothing here is asserted from belief — the three
// tables were machine-generated by diffing 44ef67f against the working tree.
//
// nl6#570 later deleted 1322 shipped ifTable .10 / .16 entries, 30 of which are
// tag-change rows below. The reversal therefore CHAINS: the test first restores
// nl6#570's ledger (reconstructing the tree nl6#541 left), then reverses the
// three tables here. Each half is separately self-evidencing, against its own
// parent digest.
//
// 44ef67f is the revision this branch FORKED FROM, not necessarily HEAD~n: the
// branch was later rebased onto a newer main (ed81427), whose resource corpus is
// byte-identical to 44ef67f's, so the ledger and the digest still describe the
// same transition. Re-derive with `git archive <base> -- go/nl6/resources` if
// that ever stops being true.

// nl6541TagChanges are the shipped entries whose EMITTED TAG changed in this
// change: 30 NVIDIA octet counters that overflowed Counter32 and one asr9k
// sysUpTime that overflowed TimeTicks, so all 31 were being served as OCTET
// STRINGs — the nl6#515 shape. Machine-generated by diffing the parent revision
// 44ef67f against the working tree with today's encoder, then committed verbatim.
var nl6541TagChanges = []struct {
	profile, oid, oldValue, newValue string
	oldTag, newTag                   byte
}{
	{"asr9k.json", ".1.3.6.1.2.1.1.3.0", "4567890123", "272922827", 0x04, 0x43},
	{"nvidia_dgx_a100.json", ".1.3.6.1.2.1.2.2.1.10.1", "98234567890", "3745287378", 0x04, 0x41},
	{"nvidia_dgx_a100.json", ".1.3.6.1.2.1.2.2.1.10.2", "2345678901234", "626757618", 0x04, 0x41},
	{"nvidia_dgx_a100.json", ".1.3.6.1.2.1.2.2.1.10.3", "2456789012345", "67719033", 0x04, 0x41},
	{"nvidia_dgx_a100.json", ".1.3.6.1.2.1.2.2.1.10.4", "2567890123456", "3794647744", 0x04, 0x41},
	{"nvidia_dgx_a100.json", ".1.3.6.1.2.1.2.2.1.10.5", "2678901234567", "3136609159", 0x04, 0x41},
	{"nvidia_dgx_a100.json", ".1.3.6.1.2.1.2.2.1.16.1", "45678901234", "2729228274", 0x04, 0x41},
	{"nvidia_dgx_a100.json", ".1.3.6.1.2.1.2.2.1.16.2", "2234567890123", "1184896203", 0x04, 0x41},
	{"nvidia_dgx_a100.json", ".1.3.6.1.2.1.2.2.1.16.3", "2345678901234", "626757618", 0x04, 0x41},
	{"nvidia_dgx_a100.json", ".1.3.6.1.2.1.2.2.1.16.4", "2456789012345", "67719033", 0x04, 0x41},
	{"nvidia_dgx_a100.json", ".1.3.6.1.2.1.2.2.1.16.5", "2567890123456", "3794647744", 0x04, 0x41},
	{"nvidia_dgx_h100.json", ".1.3.6.1.2.1.2.2.1.10.1", "98234567890", "3745287378", 0x04, 0x41},
	{"nvidia_dgx_h100.json", ".1.3.6.1.2.1.2.2.1.10.2", "2345678901234", "626757618", 0x04, 0x41},
	{"nvidia_dgx_h100.json", ".1.3.6.1.2.1.2.2.1.10.3", "2198765432109", "4037143853", 0x04, 0x41},
	{"nvidia_dgx_h100.json", ".1.3.6.1.2.1.2.2.1.10.4", "2087654321098", "300215242", 0x04, 0x41},
	{"nvidia_dgx_h100.json", ".1.3.6.1.2.1.2.2.1.10.5", "1976543210987", "858254827", 0x04, 0x41},
	{"nvidia_dgx_h100.json", ".1.3.6.1.2.1.2.2.1.16.1", "87654321098", "1754975178", 0x04, 0x41},
	{"nvidia_dgx_h100.json", ".1.3.6.1.2.1.2.2.1.16.2", "1987654321098", "3379430346", 0x04, 0x41},
	{"nvidia_dgx_h100.json", ".1.3.6.1.2.1.2.2.1.16.3", "1876543210987", "3937469931", 0x04, 0x41},
	{"nvidia_dgx_h100.json", ".1.3.6.1.2.1.2.2.1.16.4", "1765432109876", "200551220", 0x04, 0x41},
	{"nvidia_dgx_h100.json", ".1.3.6.1.2.1.2.2.1.16.5", "1654321098765", "758689805", 0x04, 0x41},
	{"nvidia_hgx_h200.json", ".1.3.6.1.2.1.2.2.1.10.1", "112345678901", "676529205", 0x04, 0x41},
	{"nvidia_hgx_h200.json", ".1.3.6.1.2.1.2.2.1.10.2", "3456789012345", "3635306361", 0x04, 0x41},
	{"nvidia_hgx_h200.json", ".1.3.6.1.2.1.2.2.1.10.3", "3567890123456", "3067267776", 0x04, 0x41},
	{"nvidia_hgx_h200.json", ".1.3.6.1.2.1.2.2.1.10.4", "3678901234567", "2409229191", 0x04, 0x41},
	{"nvidia_hgx_h200.json", ".1.3.6.1.2.1.2.2.1.10.5", "3789012345678", "851190606", 0x04, 0x41},
	{"nvidia_hgx_h200.json", ".1.3.6.1.2.1.2.2.1.16.1", "98765432109", "4276151597", 0x04, 0x41},
	{"nvidia_hgx_h200.json", ".1.3.6.1.2.1.2.2.1.16.2", "3234567890123", "457516235", 0x04, 0x41},
	{"nvidia_hgx_h200.json", ".1.3.6.1.2.1.2.2.1.16.3", "3345678901234", "4194344946", 0x04, 0x41},
	{"nvidia_hgx_h200.json", ".1.3.6.1.2.1.2.2.1.16.4", "3456789012345", "3635306361", 0x04, 0x41},
	{"nvidia_hgx_h200.json", ".1.3.6.1.2.1.2.2.1.16.5", "3567890123456", "3067267776", 0x04, 0x41},
}

// nl6541RemovedEntries are the entries this change DELETED: a bare ipRouteDest
// column OID with no instance, valued "1", in 14 profiles. Rule 3 refused it
// because that column is IpAddress-typed, so these went as a side effect of
// validation rather than as a sweep of the class; nl6#571 swept the remaining 57
// (snmp_shipped_resource_defect_ledger_test.go), which is a class no rule sees.
var nl6541RemovedEntries = []struct{ profile, oid, oldValue string }{
	{"arista_7280r3.json", ".1.3.6.1.2.1.4.21.1.1", "1"},
	{"asr9k.json", ".1.3.6.1.2.1.4.21.1.1", "1"},
	{"cisco_catalyst_9500.json", ".1.3.6.1.2.1.4.21.1.1", "1"},
	{"cisco_crs_x.json", ".1.3.6.1.2.1.4.21.1.1", "1"},
	{"cisco_ios.json", ".1.3.6.1.2.1.4.21.1.1", "1"},
	{"cisco_nexus_9500.json", ".1.3.6.1.2.1.4.21.1.1", "1"},
	{"dell_poweredge_r750.json", ".1.3.6.1.2.1.4.21.1.1", "1"},
	{"fortinet_fortigate_600e.json", ".1.3.6.1.2.1.4.21.1.1", "1"},
	{"hpe_proliant_dl380.json", ".1.3.6.1.2.1.4.21.1.1", "1"},
	{"huawei_ne8000.json", ".1.3.6.1.2.1.4.21.1.1", "1"},
	{"juniper_mx240.json", ".1.3.6.1.2.1.4.21.1.1", "1"},
	{"juniper_mx960.json", ".1.3.6.1.2.1.4.21.1.1", "1"},
	{"nokia_7750_sr12.json", ".1.3.6.1.2.1.4.21.1.1", "1"},
	{"palo_alto_pa3220.json", ".1.3.6.1.2.1.4.21.1.1", "1"},
}

// nl6541RescaledEntries are the value edits that did NOT change a tag. Every one
// sits on a leaf oidTypeTable does not type, so all of them were and remain
// INTEGER on the wire, and RULE 3 NEVER FIRED ON ANY OF THEM: five were found by
// TestShippedBigValuesSitOnCounter64Leaves (values past 2^32) and two by
// TestShippedUntypedValuesFitInteger32 (hrStorageSize.1 = 2^31 exactly, one over
// Integer32); the rest are the allocation-unit and hrStorageUsed rows rescaled
// with them so each hrStorage row stays internally consistent.
var nl6541RescaledEntries = []struct{ profile, oid, oldValue, newValue string }{
	{"nvidia_dgx_a100.json", ".1.3.6.1.2.1.25.2.3.1.4.2", "1024", "1048576"},
	{"nvidia_dgx_a100.json", ".1.3.6.1.2.1.25.2.3.1.5.2", "16106127360", "15728640"},
	{"nvidia_dgx_a100.json", ".1.3.6.1.2.1.25.2.3.1.6.2", "4831838208", "4718592"},
	{"nvidia_dgx_h100.json", ".1.3.6.1.2.1.25.2.3.1.4.1", "1024", "1048576"},
	{"nvidia_dgx_h100.json", ".1.3.6.1.2.1.25.2.3.1.4.2", "4096", "1048576"},
	{"nvidia_dgx_h100.json", ".1.3.6.1.2.1.25.2.3.1.5.1", "2147483648", "2097152"},
	{"nvidia_dgx_h100.json", ".1.3.6.1.2.1.25.2.3.1.5.2", "7864320000", "30720000"},
	{"nvidia_dgx_h100.json", ".1.3.6.1.2.1.25.2.3.1.6.1", "1288490189", "1258291"},
	{"nvidia_dgx_h100.json", ".1.3.6.1.2.1.25.2.3.1.6.2", "2359296000", "9216000"},
	{"nvidia_hgx_h200.json", ".1.3.6.1.2.1.25.2.3.1.4.1", "1024", "1048576"},
	{"nvidia_hgx_h200.json", ".1.3.6.1.2.1.25.2.3.1.4.2", "4096", "1048576"},
	{"nvidia_hgx_h200.json", ".1.3.6.1.2.1.25.2.3.1.5.1", "2147483648", "2097152"},
	{"nvidia_hgx_h200.json", ".1.3.6.1.2.1.25.2.3.1.5.2", "7864320000", "30720000"},
	{"nvidia_hgx_h200.json", ".1.3.6.1.2.1.25.2.3.1.6.1", "1503238553", "1468006"},
	{"nvidia_hgx_h200.json", ".1.3.6.1.2.1.25.2.3.1.6.2", "2621440000", "10240000"},
	{"palo_alto_pa3220.json", ".1.3.6.1.4.1.25461.2.1.2.4.1.0", "4294967296", "4194304"},
}

// shippedTagDigestBeforeDataEdits is the (profile, OID, emitted tag) digest of
// the resource corpus at 44ef67f, the revision this branch forked from, computed with
// TODAY's encoder so that the data edits are isolated from the table widening.
// The widening is separately proven tag-neutral on both corpora, which is what
// makes that isolation sound.
const shippedTagDigestBeforeDataEdits = "b0d282b46d8e0b661a20467e0ffda089b650040caca24d48fe5349b308700eef"

// TestShippedDataEditsReproduceTheParentCorpus is the before/after pin for the
// data half of nl6#541. It reverses all three tables against today's corpus and
// requires the parent digest, so the ledger cannot drift from the tree in either
// direction: a missing row, a wrong old value, or an edit made to shipped data
// without recording it here all fail.
func TestShippedDataEditsReproduceTheParentCorpus(t *testing.T) {
	type key struct{ profile, oid string }

	cur := map[key]string{}
	for _, e := range shippedSNMPEntries(t) {
		k := key{e.Profile, e.OID}
		if prev, dup := cur[k]; dup && prev != e.Value {
			t.Fatalf("%s serves %s twice with different values (%q, %q); the reconstruction "+
				"cannot be unambiguous", e.Profile, e.OID, prev, e.Value)
		}
		cur[k] = e.Value
	}

	// nl6#570 deleted every shipped ifTable .10 / .16 entry, 30 of which are
	// nl6541TagChanges rows. So the reversal chains: put those rows back first,
	// which reconstructs the tree nl6#541 left, and only then reverse nl6#541's
	// own edits. Without this step the tag-change loop below reports 30 rows as
	// "no longer shipped" and the digest cannot come back.
	// nl6#574 / nl6#571 / nl6#569 then edited shipped data again, including the
	// PAN OID .25461.2.1.2.4.1.0 that nl6541TagChanges also records, so its
	// reversal has to run first of all.
	nl6570 := map[[2]string]string{}
	for k, v := range cur {
		nl6570[[2]string{k.profile, k.oid}] = v
	}
	// nl6#591 deleted the two writeMem entries after nl6#590, so it is the
	// newest link of all and is undone first; nl6#590's Cisco-arc audit follows.
	restoreNl6591WriteMem(t, nl6570)
	restoreNl6590CiscoArc(t, nl6570)
	// nl6#576 then re-homed the NVIDIA GPU arc, which RENAMES keys rather than
	// only changing values, so it has to be undone before anything keyed on an
	// OID string runs — including the nvidia_* rescale rows below.
	restoreNl6576NvidiaArc(t, nl6570)
	restoreNl6574ResourceDefectEntries(t, nl6570)
	restoreNl6570OctetEntries(t, nl6570)
	// REBUILT, not merged. nl6#576's reversal is a RENAME, so it deletes keys as
	// well as adding them; merging back over the old map would leave both
	// spellings in the corpus and 222 phantom triples in the digest.
	cur = make(map[key]string, len(nl6570))
	for k, v := range nl6570 {
		cur[key{k[0], k[1]}] = v
	}

	// Reverse the edits.
	for _, c := range nl6541TagChanges {
		k := key{c.profile, c.oid}
		got, ok := cur[k]
		if !ok {
			t.Errorf("%s %s is in the tag-change ledger but no longer shipped", c.profile, c.oid)
			continue
		}
		if got != c.newValue {
			t.Errorf("%s %s ships %q, but the ledger says this change set it to %q",
				c.profile, c.oid, got, c.newValue)
		}
		// The tags are the claim, so assert both against the encoder rather than
		// trusting the recorded bytes.
		if enc := encodeTypedValue(c.oid, c.oldValue); len(enc) == 0 || enc[0] != c.oldTag {
			t.Errorf("%s %s: old value %q encodes as % x, ledger says tag 0x%02X",
				c.profile, c.oid, c.oldValue, enc, c.oldTag)
		}
		if enc := encodeTypedValue(c.oid, c.newValue); len(enc) == 0 || enc[0] != c.newTag {
			t.Errorf("%s %s: new value %q encodes as % x, ledger says tag 0x%02X",
				c.profile, c.oid, c.newValue, enc, c.newTag)
		}
		if c.oldTag == c.newTag {
			t.Errorf("%s %s is in the TAG-CHANGE ledger but both tags are 0x%02X; it belongs in "+
				"nl6541RescaledEntries", c.profile, c.oid, c.oldTag)
		}
		cur[k] = c.oldValue
	}
	for _, r := range nl6541RescaledEntries {
		k := key{r.profile, r.oid}
		got, ok := cur[k]
		if !ok {
			t.Errorf("%s %s is in the rescale ledger but no longer shipped", r.profile, r.oid)
			continue
		}
		if got != r.newValue {
			t.Errorf("%s %s ships %q, but the ledger says this change set it to %q",
				r.profile, r.oid, got, r.newValue)
		}
		oldEnc, newEnc := encodeTypedValue(r.oid, r.oldValue), encodeTypedValue(r.oid, r.newValue)
		if len(oldEnc) == 0 || len(newEnc) == 0 || oldEnc[0] != newEnc[0] {
			t.Errorf("%s %s: a rescale must not move the tag, but %q -> %q moves % x -> % x",
				r.profile, r.oid, r.oldValue, r.newValue, oldEnc, newEnc)
		}
		cur[k] = r.oldValue
	}
	for _, d := range nl6541RemovedEntries {
		k := key{d.profile, d.oid}
		if got, ok := cur[k]; ok {
			t.Errorf("%s %s is in the removal ledger but still ships, valued %q", d.profile, d.oid, got)
			continue
		}
		cur[k] = d.oldValue
	}

	lines := make([]string, 0, len(cur))
	for k, v := range cur {
		enc := encodeTypedValue(k.oid, v)
		if len(enc) == 0 {
			t.Fatalf("%s %s: encodeTypedValue(%q) emitted nothing", k.profile, k.oid, v)
		}
		lines = append(lines, fmt.Sprintf("%s\t%s\t%02X", k.profile, k.oid, enc[0]))
	}
	sort.Strings(lines)

	h := sha256.New()
	for _, l := range lines {
		h.Write([]byte(l))
		h.Write([]byte{'\n'})
	}
	got := hex.EncodeToString(h.Sum(nil))

	t.Logf("reversed %d tag changes, %d rescales and %d removals; %d (profile, OID, tag) triples reconstructed",
		len(nl6541TagChanges), len(nl6541RescaledEntries), len(nl6541RemovedEntries), len(lines))

	if got != shippedTagDigestBeforeDataEdits {
		t.Errorf("reconstructed parent digest = %s, want %s.\n"+
			"The ledger above no longer accounts for the difference between 44ef67f's shipped "+
			"data and this tree's. Either an edit is missing from it, or shipped data changed "+
			"without being recorded.", got, shippedTagDigestBeforeDataEdits)
	}
}

// TestShippedDataEditLedgerIsNotVacuous guards the guard: a ledger emptied (or
// a reconstruction that silently skipped it) would make the test above pass
// only if the corpus were untouched, so the counts are pinned to what the diff
// against 44ef67f actually reported.
func TestShippedDataEditLedgerIsNotVacuous(t *testing.T) {
	for _, tc := range []struct {
		name string
		got  int
		want int
	}{
		{"tag changes", len(nl6541TagChanges), 31},
		{"rescales", len(nl6541RescaledEntries), 16},
		{"removals", len(nl6541RemovedEntries), 14},
	} {
		if tc.got != tc.want {
			t.Errorf("%s: ledger has %d rows, want %d — the counts are the census reported in the "+
				"commit body and the docs, so they move together or not at all", tc.name, tc.got, tc.want)
		}
	}
	// Every tag change must be a DEGRADATION being repaired: OCTET STRING out,
	// a real type in. That is the claim the docs make about all 31.
	for _, c := range nl6541TagChanges {
		if c.oldTag != ASN1_OCTET_STRING {
			t.Errorf("%s %s: old tag 0x%02X is not OCTET STRING, so this was not the nl6#515 "+
				"degradation the change claims to have repaired", c.profile, c.oid, c.oldTag)
		}
		if c.newTag == ASN1_OCTET_STRING {
			t.Errorf("%s %s: new tag is still OCTET STRING", c.profile, c.oid)
		}
	}
}
