{{/*
Copyright 2026 Ronny Trommer <ronny@no42.org>
SPDX-License-Identifier: Apache-2.0

Only rendered when the user has NOT supplied an existing Secret.
*/}}
{{- if not .Values.minion.credentials.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nl6-minion.credentialsSecret" . }}
  labels:
    {{- include "nl6-minion.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.minion.credentials.userKey }}: {{ .Values.minion.credentials.username | quote }}
  {{ .Values.minion.credentials.passKey }}: {{ .Values.minion.credentials.password | quote }}
{{- end }}
